services:
  bob:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ADMIN_ROLES=${ADMIN_ROLES}
      - SERVER_ID=${SERVER_ID}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MINECRAFT_SERVER_IP=${MINECRAFT_SERVER_IP}
      - MINECRAFT_SERVER_PORT=${MINECRAFT_SERVER_PORT}
      - MINECRAFT_MANAGER_PORT=${MINECRAFT_MANAGER_PORT}
      - MINECRAFT_MANAGER_TOKEN=${MINECRAFT_MANAGER_TOKEN}
      - MINECRAFT_ANNOUNCE_CHANNEL_ID=${MINECRAFT_ANNOUNCE_CHANNEL_ID}
      - PROJECT_ID=${PROJECT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - APPROVE_ARTS_CHANNEL_ID=${APPROVE_ARTS_CHANNEL_ID}
      - ARTS_PANNEL_CHANNEL_ID=${ARTS_PANNEL_CHANNEL_ID}
      - NICKS_CHANNEL_ID=${NICKS_CHANNEL_ID}
      - SERVER_STATUS_CHANNEL_ID=${SERVER_STATUS_CHANNEL_ID}
      - MINECRAFT_SCREEN_NAME=${MINECRAFT_SCREEN_NAME}
      - SERVER_LOG_CHANNEL_ID=${SERVER_LOG_CHANNEL_ID}
      - TICKET_MESSAGE_ID=${TICKET_MESSAGE_ID}
      - TICKET_CATEGORY_ID=${TICKET_CATEGORY_ID}
      - ARCHIVE_TICKET_CATEGORY_ID=${ARCHIVE_TICKET_CATEGORY_ID}
      - HYBRID_STATUS_CHANNEL_ID=${HYBRID_STATUS_CHANNEL_ID}
      - SERVER_STATUS_LIST=${SERVER_STATUS_LIST}
      - AUTHOR_AUTHORIZE_CATEGORY_ID=${AUTHOR_AUTHORIZE_CATEGORY_ID}
      - PLAYER_NOTIFICATION_CHANNEL_ID=${PLAYER_NOTIFICATION_CHANNEL_ID}
      - HYBRID_NOTIFICATION_CHANNEL_ID=${HYBRID_NOTIFICATION_CHANNEL_ID}
      - HYBRID_SERVER_ID=${HYBRID_SERVER_ID}
      - MINECRAFT_FORCE_START_SCRIPT_PATH=${MINECRAFT_FORCE_START_SCRIPT_PATH}
      - GOOGLE_PROJECT=${GOOGLE_PROJECT}

    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    restart: always
    command: >
      sh -c "
        gcloud config set project $${GOOGLE_PROJECT} &&
        npm run start:prod
      "
