---
apiVersion: v1
kind: Service
metadata:
  name: bob-service-v1
spec:
  selector:
    app: bob
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      containers:
        - name: bob
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/bob/nest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
              ephemeral-storage: 1Gi
            limits:
              memory: 256Mi
              cpu: 200m
              ephemeral-storage: 1Gi
          env:
            - name: CLIENT_ID
              value: ENV_CLIENT_ID
            - name: CLIENT_SECRET
              value: ENV_CLIENT_SECRET
            - name: DISCORD_TOKEN
              value: ENV_DISCORD_TOKEN
            - name: ADMIN_ROLES
              value: ENV_ADMIN_ROLES
            - name: SERVER_ID
              value: ENV_SERVER_ID
            - name: DATABASE_URL
              value: ENV_DATABASE_URL
            - name: JWT_SECRET
              value: ENV_JWT_SECRET
            - name: MINECRAFT_SERVER_IP
              value: ENV_MINECRAFT_SERVER_IP
            - name: MINECRAFT_SERVER_PORT
              value: ENV_MINECRAFT_SERVER_PORT
            - name: MINECRAFT_MANAGER_PORT
              value: ENV_MINECRAFT_MANAGER_PORT
            - name: MINECRAFT_MANAGER_TOKEN
              value: ENV_MINECRAFT_MANAGER_TOKEN
            - name: MINECRAFT_ANNOUNCE_CHANNEL_ID
              value: ENV_MINECRAFT_ANNOUNCE_CHANNEL_ID
