---
apiVersion: v1
kind: Service
metadata:
  name: bob-service-v1
spec:
  selector:
    app: bob
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      containers:
        - name: bob
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/PROJECT_NAME/IMAGE_NAME
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
              ephemeral-storage: 1Gi
            limits:
              memory: 512Mi
              cpu: 300m
              ephemeral-storage: 2Gi
          env:
            - name: CLIENT_ID
              value: ENV_CLIENT_ID
            - name: CLIENT_SECRET
              value: ENV_CLIENT_SECRET
            - name: DISCORD_TOKEN
              value: ENV_DISCORD_TOKEN
            - name: ADMIN_ROLES
              value: ENV_ADMIN_ROLES
            - name: SERVER_ID
              value: ENV_SERVER_ID
            - name: DATABASE_URL
              value: ENV_DATABASE_URL
            - name: JWT_SECRET
              value: ENV_JWT_SECRET
            - name: MINECRAFT_SERVER_IP
              value: ENV_MINECRAFT_SERVER_IP
            - name: MINECRAFT_SERVER_PORT
              value: ENV_MINECRAFT_SERVER_PORT
            - name: MINECRAFT_MANAGER_PORT
              value: ENV_MINECRAFT_MANAGER_PORT
            - name: MINECRAFT_MANAGER_TOKEN
              value: ENV_MINECRAFT_MANAGER_TOKEN
            - name: MINECRAFT_ANNOUNCE_CHANNEL_ID
              value: ENV_MINECRAFT_ANNOUNCE_CHANNEL_ID
            - name: PROJECT_ID
              value: ENV_PROJECT_ID
            - name: BUCKET_NAME
              value: ENV_BUCKET_NAME
            - name: APPROVE_ARTS_CHANNEL_ID
              value: ENV_APPROVE_ARTS_CHANNEL_ID
            - name: ARTS_PANNEL_CHANNEL_ID
              value: ENV_ARTS_PANNEL_CHANNEL_ID
            - name: NICKS_CHANNEL_ID
              value: ENV_NICKS_CHANNEL_ID
            - name: SERVER_STATUS_CHANNEL_ID
              value: ENV_SERVER_STATUS_CHANNEL_ID
            - name: MINECRAFT_SCREEN_NAME
              value: ENV_MINECRAFT_SCREEN_NAME
            - name: SERVER_LOG_CHANNEL_ID
              value: ENV_SERVER_LOG_CHANNEL_ID
            - name: TICKET_MESSAGE_ID
              value: ENV_TICKET_MESSAGE_ID
            - name: TICKET_CATEGORY_ID
              value: ENV_TICKET_CATEGORY_ID
            - name: ARCHIVE_TICKET_CATEGORY_ID
              value: ENV_ARCHIVE_TICKET_CATEGORY_ID
            - name: HYBRID_STATUS_CHANNEL_ID
              value: ENV_HYBRID_STATUS_CHANNEL_ID
            - name: SERVER_STATUS_LIST
              value: ENV_SERVER_STATUS_LIST
            - name: AUTHOR_AUTHORIZE_CATEGORY_ID
              value: ENV_AUTHOR_AUTHORIZE_CATEGORY_ID
            - name: PLAYER_NOTIFICATION_CHANNEL_ID
              value: ENV_PLAYER_NOTIFICATION_CHANNEL_ID
            - name: HYBRID_NOTIFICATION_CHANNEL_ID
              value: ENV_HYBRID_NOTIFICATION_CHANNEL_ID
